# Generated by Django 3.0.3 on 2020-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
