# Generated by Django 3.0.3 on 2020-02-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
