# Generated by Django 3.0.3 on 2020-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
    ]
