# Generated by Django 3.0.3 on 2020-03-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comments_news_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
