# Generated by Django 3.0.3 on 2020-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='prev_text',
            field=models.TextField(default=''),
        ),
    ]
