# Generated by Django 3.0.3 on 2020-03-13 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0013_auto_20200313_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtended',
            new_name='Extended',
        ),
        migrations.RenameField(
            model_name='extended',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
