# Generated by Django 3.0.3 on 2020-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200313_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Extended',
        ),
    ]
